# Generated by Django 3.1.5 on 2021-02-06 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('happyworld', '0008_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='happyworld.genre', verbose_name='Genre'),
        ),
        migrations.AddField(
            model_name='book',
            name='publishing_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='happyworld.publishing', verbose_name='Publishing'),
        ),
        migrations.AddField(
            model_name='book',
            name='series_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='happyworld.series', verbose_name='Series'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='happyworld.author', verbose_name='Author'),
        ),
    ]
