# Generated by Django 3.1.5 on 2021-02-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyworld', '0009_auto_20210206_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='descriptions_book',
            field=models.TextField(blank=True, null=True, verbose_name='Descriptions book'),
        ),
        migrations.AddField(
            model_name='book',
            name='year_publishing',
            field=models.PositiveSmallIntegerField(default='0', verbose_name='Year publishing'),
            preserve_default=False,
        ),
    ]
