# Generated by Django 3.1.5 on 2021-02-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyworld', '0011_auto_20210206_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='descriptions_book',
            field=models.TextField(blank=True, null=True, verbose_name='Descriptions book'),
        ),
    ]
