# Generated by Django 3.1.5 on 2021-02-13 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('happyworld', '0013_auto_20210207_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='Имя пользователя')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя')),
                ('email', models.EmailField(help_text='Enter a valid email addres', max_length=100)),
                ('password1', models.CharField(max_length=30)),
                ('password2', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AccountProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='happyworld.user')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя')),
                ('email', models.CharField(help_text='Электронная почта', max_length=100)),
                ('phone_number', models.IntegerField(blank=True, null=True, verbose_name='Мобильный номер')),
            ],
        ),
    ]
