# Generated by Django 3.1.5 on 2021-02-16 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('happyworld', '0017_auto_20210215_2124'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
