# Generated by Django 3.1.5 on 2021-03-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210313_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='total_sum',
        ),
        migrations.AddField(
            model_name='cart',
            name='total_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма'),
        ),
    ]
