# Generated by Django 3.1.5 on 2021-03-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210313_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_sum',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
    ]
