# Generated by Django 3.1.5 on 2021-03-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20210315_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='price_sum',
            new_name='price_sum_item',
        ),
        migrations.AddField(
            model_name='cart',
            name='total_sum_cart',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма'),
        ),
    ]
