# Generated by Django 3.1.5 on 2021-03-15 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20210315_2119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='price_sum_item',
            new_name='total_sum_item',
        ),
    ]
