# Generated by Django 3.1.5 on 2021-03-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20210321_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='actions',
            field=models.BooleanField(default=True, verbose_name='Заказ подтвержден'),
        ),
    ]
