# Generated by Django 3.1.5 on 2021-03-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_order_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='actions',
            field=models.CharField(choices=[('Confirmed', 'Подтвержден'), ('Выполнен', 'Done'), ('Canceled', 'Отменен')], default='Confirmed', max_length=15, verbose_name='Статус заказа'),
        ),
    ]
