# Generated by Django 3.1.5 on 2021-03-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_auto_20210321_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='actions',
            field=models.CharField(choices=[('Подтвержден', 'Confirmed'), ('Выполнен', 'Done'), ('Отменен', 'Canceled')], default='Подтвержден', max_length=15, verbose_name='Статус заказа'),
        ),
    ]
