# Generated by Django 3.1.5 on 2021-02-21 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('username', models.OneToOneField(max_length=30, on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='auth.user', verbose_name='Имя пользователя')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя')),
                ('email', models.EmailField(help_text='Enter a valid email addres', max_length=100)),
                ('password1', models.CharField(max_length=30)),
                ('password2', models.CharField(max_length=30)),
                ('country', models.CharField(blank=True, max_length=30, null=True, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=40, null=True, verbose_name='Город')),
                ('zip_code', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Индекс')),
                ('address_first', models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес1')),
                ('address_second', models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес2')),
                ('info', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Дополнительная информация')),
            ],
        ),
    ]
