# Generated by Django 3.1.5 on 2021-03-06 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('profiles', '0003_profile_group_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='group_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.group'),
        ),
    ]
