# Generated by Django 3.1.5 on 2021-03-06 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('profiles', '0004_auto_20210306_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='group_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auth.group'),
        ),
    ]
