# Generated by Django 3.1.5 on 2021-01-31 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0003_auto_20210131_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_genre', models.CharField(max_length=30, verbose_name='Name genre?')),
            ],
        ),
        migrations.RenameModel(
            old_name='Authors',
            new_name='Author',
        ),
    ]
