# Generated by Django 3.1.5 on 2021-02-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0006_auto_20210204_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='descriptions',
            field=models.TextField(blank=True, null=True, verbose_name='Descriptions Author'),
        ),
    ]
