# Generated by Django 3.1.5 on 2021-02-21 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0018_delete_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
