# Generated by Django 3.1.5 on 2021-02-16 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('happyworld', '0018_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_book', models.CharField(max_length=100, verbose_name='Name book')),
                ('descriptions_book', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Descriptions book')),
                ('year_publishing', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Year publishing')),
                ('number_of_pages', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Number of page')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created date')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Updated date')),
                ('photo_book', models.ImageField(blank=True, null=True, upload_to='books/', verbose_name='Фото книги')),
                ('author_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='happyworld.author', verbose_name='Author')),
                ('genre_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='happyworld.genre', verbose_name='Genre')),
                ('publishing_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='happyworld.publishing', verbose_name='Publishing')),
                ('series_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='happyworld.series', verbose_name='Series')),
            ],
        ),
    ]
