# Generated by Django 3.1.5 on 2021-02-17 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photo_book',
        ),
        migrations.CreateModel(
            name='ImageProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image_product')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created date')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Updated date')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.product')),
            ],
        ),
    ]
