# Generated by Django 3.1.5 on 2021-02-17 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210217_2035'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageProduct',
            new_name='ProductsImage',
        ),
    ]
