# Generated by Django 3.1.5 on 2021-02-20 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0018_delete_book'),
        ('product', '0004_auto_20210220_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='age_restrictions',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Возрастные ограничения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='author_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='references.author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='product',
            name='descriptions_book',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Описание книги'),
        ),
        migrations.AlterField(
            model_name='product',
            name='genre_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='references.genre', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='product',
            name='isbn',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_book',
            field=models.CharField(max_length=100, verbose_name='Название книги'),
        ),
        migrations.AlterField(
            model_name='product',
            name='number_of_pages',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество страниц'),
        ),
        migrations.AlterField(
            model_name='product',
            name='publishing_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='references.publishing', verbose_name='Издательство'),
        ),
        migrations.AlterField(
            model_name='product',
            name='series_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='references.series', verbose_name='Серия'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Вес книги'),
        ),
        migrations.AlterField(
            model_name='product',
            name='year_publishing',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год издания'),
        ),
    ]
